/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.pkg1.edd.grupo8.ass;

import javax.swing.JOptionPane;

/**
 *
 * @author sebas
 */
public class VentanaGrafo extends javax.swing.JFrame {
    public static GrafoMatriz grafo;
    /**
     * Creates new form VentanaGrafo
     */
    public VentanaGrafo(GrafoMatriz grafo) {
        initComponents();
        
        this.grafo= grafo;
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        exit = new javax.swing.JToggleButton();
        back = new javax.swing.JButton();
        mostrarGrafo = new javax.swing.JButton();
        mostrarPuentes = new javax.swing.JButton();
        modificarGrafo = new javax.swing.JButton();
        mostrarIslasDFS = new javax.swing.JButton();
        mostrarIslasBFS = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        pantallaGrafo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setBackground(new java.awt.Color(204, 0, 0));
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("X");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 30));

        back.setBackground(new java.awt.Color(51, 51, 51));
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText(">>>");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, 70, -1));

        mostrarGrafo.setBackground(new java.awt.Color(51, 51, 51));
        mostrarGrafo.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        mostrarGrafo.setForeground(new java.awt.Color(255, 255, 255));
        mostrarGrafo.setText("MOSTRAR GRAFO");
        mostrarGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarGrafoActionPerformed(evt);
            }
        });
        jPanel1.add(mostrarGrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 280, 50));

        mostrarPuentes.setBackground(new java.awt.Color(51, 51, 51));
        mostrarPuentes.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        mostrarPuentes.setForeground(new java.awt.Color(255, 255, 255));
        mostrarPuentes.setText("MOSTRAR CANTIDAD DE PUENTES");
        mostrarPuentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarPuentesActionPerformed(evt);
            }
        });
        jPanel1.add(mostrarPuentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 250, 50));

        modificarGrafo.setBackground(new java.awt.Color(51, 51, 51));
        modificarGrafo.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        modificarGrafo.setForeground(new java.awt.Color(255, 255, 255));
        modificarGrafo.setText("MODIFICAR GRAFO");
        modificarGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarGrafoActionPerformed(evt);
            }
        });
        jPanel1.add(modificarGrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 250, 50));

        mostrarIslasDFS.setBackground(new java.awt.Color(51, 51, 51));
        mostrarIslasDFS.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        mostrarIslasDFS.setForeground(new java.awt.Color(255, 255, 255));
        mostrarIslasDFS.setText("MOSTRAR ISLAS DFS");
        mostrarIslasDFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarIslasDFSActionPerformed(evt);
            }
        });
        jPanel1.add(mostrarIslasDFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 280, 50));

        mostrarIslasBFS.setBackground(new java.awt.Color(51, 51, 51));
        mostrarIslasBFS.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        mostrarIslasBFS.setForeground(new java.awt.Color(255, 255, 255));
        mostrarIslasBFS.setText("MOSTRAR ISLAS BFS");
        mostrarIslasBFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarIslasBFSActionPerformed(evt);
            }
        });
        jPanel1.add(mostrarIslasBFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 280, 50));

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 190, -1));

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MENU GRAFO");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 270, -1));

        pantallaGrafo.setEditable(false);
        pantallaGrafo.setBackground(new java.awt.Color(51, 51, 51));
        pantallaGrafo.setColumns(20);
        pantallaGrafo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        pantallaGrafo.setForeground(new java.awt.Color(255, 255, 255));
        pantallaGrafo.setRows(5);
        pantallaGrafo.setAutoscrolls(false);
        jScrollPane3.setViewportView(pantallaGrafo);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 560, 110));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarIslasBFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarIslasBFSActionPerformed
        if (grafo != null && !grafo.getLista_usuarios().estaVacia()) {
            pantallaGrafo.setText("");
            Object[] objeto = grafo.CantidadIslasBFS();
            pantallaGrafo.setText(objeto[1]+"\n"+"La cantidad de islas por BFS es: "+objeto[0]);
        }else{
            pantallaGrafo.setText("No hay Islas existentes");
        }
    }//GEN-LAST:event_mostrarIslasBFSActionPerformed

    private void mostrarIslasDFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarIslasDFSActionPerformed
        if (grafo != null && !grafo.getLista_usuarios().estaVacia()) {
            pantallaGrafo.setText("");
            grafo.CantidadIslasDFS(pantallaGrafo);
        }else{
            pantallaGrafo.setText("No hay Islas existentes");
        }
    }//GEN-LAST:event_mostrarIslasDFSActionPerformed

    private void modificarGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarGrafoActionPerformed
        this.dispose();
        new VentanaModificarGrafo(grafo).setVisible(true);
    }//GEN-LAST:event_modificarGrafoActionPerformed

    private void mostrarPuentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarPuentesActionPerformed
        if (grafo != null) {
            grafo.IdentificadorPuentes(pantallaGrafo);
        }else{
            pantallaGrafo.setText("No hay usuarios en la base de datos");
        }
    }//GEN-LAST:event_mostrarPuentesActionPerformed

    private void mostrarGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarGrafoActionPerformed
        if (grafo != null && !grafo.getLista_usuarios().estaVacia()) {
            grafo.mostrarGrafo();
        }else{
            pantallaGrafo.setText("No hay usuarios en la base de datos");
        }
    }//GEN-LAST:event_mostrarGrafoActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.dispose();
        new VentanaInicio(grafo).setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaGrafo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaGrafo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaGrafo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaGrafo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaGrafo(grafo).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JToggleButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton modificarGrafo;
    private javax.swing.JButton mostrarGrafo;
    private javax.swing.JButton mostrarIslasBFS;
    private javax.swing.JButton mostrarIslasDFS;
    private javax.swing.JButton mostrarPuentes;
    private javax.swing.JTextArea pantallaGrafo;
    // End of variables declaration//GEN-END:variables
}
